# Generated by Django 4.1.7 on 2023-02-23 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("birth_year", models.SmallIntegerField(blank=True, null=True)),
                ("death_year", models.SmallIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("download_count", models.IntegerField(default=0)),
                ("gutenberg_id", models.IntegerField()),
                ("media_type", models.CharField(max_length=16)),
                ("title", models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bookshelf",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Format",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("mime_type", models.CharField(max_length=32)),
                ("url", models.CharField(max_length=256)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookquery.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookSubject",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("subject_id", models.IntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookquery.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookLanguage",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("language_id", models.IntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookquery.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookBookshelf",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("bookshelf_id", models.IntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookquery.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookAuthor",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookquery.author",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookquery.book"
                    ),
                ),
            ],
        ),
    ]
