# Generated by Django 4.1.7 on 2023-02-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookquery", "0003_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=155)),
            ],
        ),
    ]
