# Generated by Django 4.1.7 on 2023-02-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookquery", "0002_alter_book_download_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=5)),
            ],
        ),
    ]
