version: "3"

services:
  book_app:
    container_name: book_app
    image: postgres
    environment:
      POSTGRES_USER: "book_user"
      POSTGRES_PASSWORD: "book_123"
      PGDATA: /data/book_app
    volumes:
      - book_app:/data/book_app
    ports:
      - "5434:5432"
    networks:
      - book_app_net
    restart: unless-stopped

networks:
  book_app_net:
    driver: bridge

volumes:
  book_app:
